name: cpcheckout
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cloud-ea-second/cpcheckout@v3
      - name: Run a one-line script
        run: echo Hello, world!
